# Generated by Django 6.0.6 on 2026-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
            ],
            options={
                'verbose_name': 'Configuracion del sitio',
                'verbose_name_plural': 'Configuracion del sitio',
            },
        ),
    ]
