# Generated by Django 6.0.6 on 2026-06-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-folder', help_text='Clase de Font Awesome o Simple Icons. Ej: fa-brands fa-linux', max_length=100),
        ),
    ]
