# Generated by Django 6.0.6 on 2026-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Pablo Gutiérrez Gracia', max_length=100)),
                ('cargo', models.CharField(default='Responsable de Sistemas', max_length=200)),
                ('empresa', models.CharField(default='Texco Solutions SL', max_length=200)),
                ('ubicacion', models.CharField(default='Almodóvar del Río, Córdoba, España', max_length=200)),
                ('email', models.EmailField(default='pgutigracia@gmail.com', max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('stack', models.TextField(blank=True, help_text='Formato JSON: {"sistemas": "Windows, Linux", "cloud": "M365"}')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
            },
        ),
    ]
