# Generated by Django 6.0.6 on 2026-06-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificaciones',
            field=models.TextField(blank=True, help_text='Lista de certificaciones separadas por comas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experiencia',
            field=models.TextField(blank=True, help_text='Describe tu experiencia profesional en texto libre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='formacion',
            field=models.TextField(blank=True, help_text='Describe tu formación académica en texto libre'),
        ),
    ]
