# Generated by Django 6.0.6 on 2026-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_profile_certificaciones_profile_experiencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('author_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token LinkedIn',
                'verbose_name_plural': 'Token LinkedIn',
            },
        ),
    ]
