# Generated by Django 6.0.6 on 2026-06-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_linkedintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas. Ej: linux, docker, ansible', max_length=300),
        ),
    ]
