# Generated by Django 6.0.6 on 2026-06-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='linkedin_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='linkedin_scheduled',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de publicación en LinkedIn', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='linkedin_text',
            field=models.TextField(blank=True, help_text='Texto personalizado para LinkedIn. Si se deja vacío se usará el título.'),
        ),
    ]
