# Generated by Django 6.0.6 on 2026-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_article_linkedin_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Imagen destacada del articulo', null=True, upload_to='articles/'),
        ),
    ]
