# Generated by Django 6.0.6 on 2026-06-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_article_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='linkedin_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
