# Generated by Django 6.0.6 on 2026-06-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_article_linkedin_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_scheduled',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora a la que se publicará automáticamente el artículo en la wiki', null=True),
        ),
    ]
