# Generated by Django 6.0.6 on 2026-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_article_publish_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
