# Generated by Django 6.0.6 on 2026-07-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_article_publish_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(default='/admin/', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intento honeypot',
                'verbose_name_plural': 'Intentos honeypot',
                'ordering': ['-created_at'],
            },
        ),
    ]
