# Generated by Django 6.0.6 on 2026-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_honeypotattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='embedding_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
