# Generated by Django 6.0.6 on 2026-10-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_article_embedding_article_embedding_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('embedding', models.TextField(blank=True, default='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='wiki.article')),
            ],
            options={
                'ordering': ['article_id', 'idx'],
            },
        ),
    ]
